#!/bin/bash
#Code to make sure the leds are off when the server starts up and also to setup the pulls on the other pins
#Measuring stick
#Inputs BCM
#	5
#	6
#	7
#	8
#	11
#	13
#	16
#	19
#	20
#	21
#	23
#	24
#	25
#	26
#Outputs
#	12
#Lights outputs
#	2
#	3
#	4
#	14
#	15
#	17
#	18

declare -a water_in
leds=(18 15 4 14 3 17 2) #Leds in sequence from led 1 to led 7
leds_len=7 #set to length of leds array
declare -a water_in
water_in=(23 7 6 20 5 25 24 13 21 19 26 16 8 11) #water measuring stick input pins
water_in_len=14 #set to length of water_in array
water_out=12 #water measuring stick output pin

gpio -g write $water_out 0 #make sure output pin is off

#Configure internal (~50k) pull-down on the water measuring stick inputs
for ((i=0; i<$water_in_len; i++));
do
	gpio -g mode ${water_in[$i]} down
done

#Turn off all of the leds (automatically turned tho show when booting)
for ((i=0; i<$leds_len; i++));
do
	gpio -g write ${leds[$i]} 0
done

